-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         8.0.30 - MySQL Community Server - GPL
-- SO del servidor:              Win64
-- HeidiSQL Versión:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Volcando estructura de base de datos para atencion
CREATE DATABASE IF NOT EXISTS `atencion` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `atencion`;

-- Volcando estructura para tabla atencion.cargos
CREATE TABLE IF NOT EXISTS `cargos` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `cargo` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  `band` int NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=65 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

-- Volcando datos para la tabla atencion.cargos: ~64 rows (aproximadamente)
INSERT INTO `cargos` (`id`, `cargo`, `band`) VALUES
	(1, 'PRESIDENTE', 1),
	(2, 'GERENTE DE OPERACIONES Y LOGISTICA', 1),
	(3, 'GERENTE DE ADMINISTRACION Y COMERCIALIZACION', 1),
	(4, 'INSPECTOR DE GESTION', 1),
	(5, 'JEFE DE BIENES', 1),
	(6, 'JEFE DE SERVICIOS GENERALES', 1),
	(7, 'JEFE DE CONTABILIDAD', 1),
	(8, 'SUPERVISOR (A) DE CENTRO DE EMP. (MUN. CAMAGUAN)', 1),
	(9, 'JEFE DE ALMACEN', 1),
	(10, 'DIRECTOR (A) DE PLANIFICACION Y PRESUPUESTO', 1),
	(11, 'SUPERVISOR DE ALMACEN', 1),
	(12, 'DIRECTOR (A) OPERACIONES', 1),
	(13, 'JEFE DE TRANSPORTE', 1),
	(14, 'DIRECTOR (A) DE TALENTO HUMANO', 1),
	(15, 'ANALISTA ADMINISTRATIVO', 1),
	(16, 'JEFE DE NOMINA', 1),
	(17, 'CONSULTORIA JURIDICA', 1),
	(18, 'DIRECTOR PLANIF. DISTRIBUCION Y ESTADISTICA', 1),
	(19, 'DIRECTOR (A) DE TIENDA EN LINEA', 1),
	(20, 'JEFE DE CENTRO DE EMPAQUETADO INFANTE', 1),
	(21, 'JEFE DE FACTURACION', 1),
	(22, 'DIRECTOR (A) DE CONTROL Y SEGUIMIENTO', 1),
	(23, 'JEFE DE CENTRO DE EMPAQUETADO ROSCIO', 1),
	(24, 'DIRECTOR DE COMERCIALIZACION', 1),
	(25, 'SUPERVISORA DE CENTRO DE EMPAQUETADO INFANTE', 1),
	(26, 'SUPERVISOR DE OPERACIONES', 1),
	(27, 'DIRECTOR DE SISTEMA Y TECNOLOGIA', 1),
	(28, 'JEFE DE TIENDA', 1),
	(29, 'JEFE DE CONTROL DE CALIDAD', 1),
	(30, 'JEFE DE ATENCION AL CIUDADANO', 1),
	(31, 'JEFE DE PRENSA Y COMUNICACION', 1),
	(32, 'JEFE DE MERCADEO', 1),
	(33, 'JEFE DE CAJA', 1),
	(34, 'JEFE DE TESORERIA', 1),
	(35, 'ANALISTA DE COBRANZA I', 1),
	(36, 'DIRECTOR DE TIENDA', 1),
	(37, 'SUPERVISOR DE TIENDA', 1),
	(38, 'ANALISTA DE FACTURACION I', 1),
	(39, 'ANALISTA DE LA GERENCIA DE OP. Y LOGISTICA', 1),
	(40, 'ANALISTA DE COBRANZA', 1),
	(41, 'ALMACENISTA I', 1),
	(42, 'ANALISTA DE PERSONAL', 1),
	(43, 'ANALISTA CONTABLE', 1),
	(44, 'CAJERO (A)', 1),
	(45, 'ANALISTA DE CONTROL DE CALIDAD', 1),
	(46, 'ANALISTA DE FACTURACION', 1),
	(47, 'ANALISTA DE MERCADEO', 1),
	(48, 'ASISTENTE DE LA GERENCIA ADMINISTRATIVA Y COMERCIALIZACION', 1),
	(49, 'ASISTENTE CONSULTORIA', 1),
	(50, 'ANALISTA DE SOPORTE TECNICO', 1),
	(51, 'ANALISTA DE TESORERIA', 1),
	(52, 'ANALISTA DE ESTADISTICA', 1),
	(53, 'RECEPCIONISTA ', 1),
	(54, 'ANALISTA DE ALMACEN', 1),
	(55, 'ANALISTA DE BIENES', 1),
	(56, 'COMUNICADOR SOCIAL', 1),
	(57, 'ASISTENTE DE PRESIDENCIA', 1),
	(58, 'SEGURIDAD', 1),
	(59, 'VIGILANTE', 1),
	(60, 'OBRERO (A)', 1),
	(61, 'OBRERO CHOFER', 1),
	(62, 'CARGA Y DESCARGA', 1),
	(63, 'MANTENIMIENTO', 1),
	(64, 'PASILLERO (A)', 1);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
